import json
import sys
import os
sys.path.append(os.getcwd())
try:
    from scripts.generate_map import grid_str, colors
except ImportError:
    print("Failed to import")
    sys.exit(1)

lines = [l.strip().split() for l in grid_str.strip().split('\n')]
H = len(lines)
W = max(len(r) for r in lines)
grid = [row + ['..'] * (W - len(row)) for row in lines]

adj = {s: set() for s in colors.keys()}
for y in range(H):
    for x in range(W):
        s1 = grid[y][x]
        if s1 == '..': continue
        if s1 not in adj: adj[s1] = set()
        for dy, dx in [(-1,0), (1,0), (0,-1), (0,1)]:
            ny, nx = y+dy, x+dx
            if 0 <= ny < H and 0 <= nx < W:
                s2 = grid[ny][nx]
                if s2 != '..' and s2 != s1:
                    adj[s1].add(s2)

all_adj = {s: list(adj[s]) for s in adj if s in colors}

ts_content = f"""// Auto-generated by extract_adj.py
export const stateColors: {{ [key: string]: string }} = {json.dumps(colors, indent=2)};
export const stateAdjacencies: {{ [key: string]: string[] }} = {json.dumps(all_adj, indent=2)};
"""

with open('src/app/map-data.ts', 'w') as f:
    f.write(ts_content)
print("Exported map-data.ts")
