// Auto-generated by extract_adj.py
export const stateColors: { [key: string]: string } = {
  "AK": "ra-orange",
  "HI": "ra-orange",
  "WA": "ra-orange",
  "OR": "ra-orange",
  "ID": "ra-orange",
  "UT": "ra-orange",
  "AZ": "ra-orange",
  "NV": "ra-orange",
  "CA": "ra-orange",
  "MT": "ra-blue",
  "ND": "ra-blue",
  "SD": "ra-blue",
  "MN": "ra-blue",
  "IA": "ra-blue",
  "WI": "ra-blue",
  "IL": "ra-blue",
  "IN": "ra-blue",
  "MI": "ra-blue",
  "WY": "ra-green",
  "NE": "ra-green",
  "KS": "ra-green",
  "CO": "ra-green",
  "NM": "ra-green",
  "OK": "ra-green",
  "TX": "ra-green",
  "MO": "ra-yellow",
  "AR": "ra-yellow",
  "LA": "ra-yellow",
  "AL": "ra-yellow",
  "TN": "ra-yellow",
  "MS": "ra-yellow",
  "FL": "ra-yellow",
  "KY": "ra-yellow",
  "DE": "ra-red",
  "MD": "ra-red",
  "PA": "ra-red",
  "OH": "ra-red",
  "WV": "ra-red",
  "VA": "ra-red",
  "NC": "ra-red",
  "SC": "ra-red",
  "GA": "ra-red",
  "ME": "ra-purple",
  "NH": "ra-purple",
  "VT": "ra-purple",
  "NY": "ra-purple",
  "MA": "ra-purple",
  "RI": "ra-purple",
  "CT": "ra-purple",
  "NJ": "ra-purple"
};
export const stateAdjacencies: { [key: string]: string[] } = {
  "AK": [],
  "HI": [],
  "WA": [
    "OR",
    "ID"
  ],
  "OR": [
    "ID",
    "NV",
    "CA",
    "WA"
  ],
  "ID": [
    "NV",
    "UT",
    "WA",
    "MT",
    "OR"
  ],
  "UT": [
    "NV",
    "ID",
    "SD",
    "AZ",
    "WY"
  ],
  "AZ": [
    "CO",
    "NV",
    "UT",
    "TX",
    "NM",
    "CA",
    "WY"
  ],
  "NV": [
    "UT",
    "ID",
    "OR",
    "AZ",
    "CA"
  ],
  "CA": [
    "OR",
    "NV",
    "AZ"
  ],
  "MT": [
    "ID",
    "ND",
    "SD"
  ],
  "ND": [
    "MT",
    "SD",
    "MN"
  ],
  "SD": [
    "WY",
    "UT",
    "MN",
    "IA",
    "MT",
    "NE",
    "ND"
  ],
  "MN": [
    "IA",
    "WI",
    "ND",
    "SD"
  ],
  "IA": [
    "WI",
    "IL",
    "SD",
    "MN"
  ],
  "WI": [
    "MI",
    "NY",
    "MN",
    "IL",
    "IA"
  ],
  "IL": [
    "IA",
    "IN",
    "WI",
    "NE"
  ],
  "IN": [
    "MI",
    "LA",
    "KS",
    "IL",
    "NE"
  ],
  "MI": [
    "WI",
    "NY",
    "TN",
    "IN",
    "NJ"
  ],
  "WY": [
    "CO",
    "UT",
    "SD",
    "AZ",
    "NE"
  ],
  "NE": [
    "CO",
    "KS",
    "IN",
    "IL",
    "SD",
    "WY"
  ],
  "KS": [
    "CO",
    "LA",
    "OK",
    "IN",
    "NE",
    "AR"
  ],
  "CO": [
    "OK",
    "KS",
    "NM",
    "AZ",
    "NE",
    "WY"
  ],
  "NM": [
    "CO",
    "OK",
    "TX",
    "AZ"
  ],
  "OK": [
    "CO",
    "TX",
    "KS",
    "NM",
    "AR"
  ],
  "TX": [
    "AR",
    "NM",
    "OK",
    "AZ"
  ],
  "MO": [
    "TN",
    "LA",
    "AR"
  ],
  "AR": [
    "AL",
    "OK",
    "TX",
    "TN",
    "KS",
    "FL",
    "MO"
  ],
  "LA": [
    "KS",
    "IN",
    "MO",
    "TN"
  ],
  "AL": [
    "SC",
    "KY",
    "TN",
    "MS",
    "VA",
    "AR"
  ],
  "TN": [
    "MI",
    "LA",
    "AL",
    "MS",
    "AR",
    "MO"
  ],
  "MS": [
    "TN",
    "AL",
    "NJ",
    "KY"
  ],
  "FL": [
    "AR"
  ],
  "KY": [
    "MS",
    "AL",
    "CT",
    "WV"
  ],
  "DE": [
    "RI",
    "PA",
    "MD"
  ],
  "MD": [
    "PA",
    "DE",
    "NC"
  ],
  "PA": [
    "CT",
    "MD",
    "DE",
    "OH",
    "VA",
    "WV"
  ],
  "OH": [
    "PA",
    "CT",
    "WV"
  ],
  "WV": [
    "VA",
    "OH",
    "PA",
    "KY"
  ],
  "VA": [
    "SC",
    "AL",
    "PA",
    "NC",
    "WV"
  ],
  "NC": [
    "VA",
    "GA",
    "MD"
  ],
  "SC": [
    "VA",
    "AL",
    "GA"
  ],
  "GA": [
    "SC",
    "NC"
  ],
  "ME": [
    "NH"
  ],
  "NH": [
    "VT",
    "ME",
    "MA"
  ],
  "VT": [
    "NH",
    "MA",
    "NY"
  ],
  "NY": [
    "MI",
    "WI",
    "CT",
    "MA",
    "VT",
    "NJ"
  ],
  "MA": [
    "CT",
    "NY",
    "NH",
    "RI",
    "VT"
  ],
  "RI": [
    "CT",
    "DE",
    "MA"
  ],
  "CT": [
    "PA",
    "NY",
    "KY",
    "MA",
    "OH",
    "RI",
    "NJ"
  ],
  "NJ": [
    "MS",
    "CT",
    "MI",
    "NY"
  ]
};
