// Auto-generated by extract_adj.py
export const stateColors: { [key: string]: string } = {
  "AK": "ra-orange",
  "HI": "ra-orange",
  "WA": "ra-orange",
  "OR": "ra-orange",
  "ID": "ra-orange",
  "UT": "ra-orange",
  "AZ": "ra-orange",
  "NV": "ra-orange",
  "CA": "ra-orange",
  "MT": "ra-blue",
  "ND": "ra-blue",
  "SD": "ra-blue",
  "MN": "ra-blue",
  "IA": "ra-blue",
  "WI": "ra-blue",
  "IL": "ra-blue",
  "IN": "ra-blue",
  "MI": "ra-blue",
  "WY": "ra-green",
  "NE": "ra-green",
  "KS": "ra-green",
  "CO": "ra-green",
  "NM": "ra-green",
  "OK": "ra-green",
  "TX": "ra-green",
  "MO": "ra-yellow",
  "AR": "ra-yellow",
  "LA": "ra-yellow",
  "AL": "ra-yellow",
  "TN": "ra-yellow",
  "MS": "ra-yellow",
  "FL": "ra-yellow",
  "KY": "ra-yellow",
  "DE": "ra-red",
  "MD": "ra-red",
  "PA": "ra-red",
  "OH": "ra-red",
  "WV": "ra-red",
  "VA": "ra-red",
  "NC": "ra-red",
  "SC": "ra-red",
  "GA": "ra-red",
  "ME": "ra-purple",
  "NH": "ra-purple",
  "VT": "ra-purple",
  "NY": "ra-purple",
  "MA": "ra-purple",
  "RI": "ra-purple",
  "CT": "ra-purple",
  "NJ": "ra-purple"
};
export const stateAdjacencies: { [key: string]: string[] } = {
  "ME": [
    "NH"
  ],
  "VT": [
    "MA",
    "NH",
    "NY"
  ],
  "NH": [
    "MA",
    "ME",
    "VT"
  ],
  "AK": [],
  "WA": [
    "ID",
    "OR"
  ],
  "ID": [
    "MT",
    "NV",
    "OR",
    "UT",
    "WA",
    "WY"
  ],
  "MT": [
    "ID",
    "ND",
    "SD",
    "WY"
  ],
  "ND": [
    "MN",
    "MT",
    "SD"
  ],
  "MN": [
    "IA",
    "ND",
    "SD",
    "WI"
  ],
  "NY": [
    "CT",
    "MA",
    "NJ",
    "PA",
    "VT"
  ],
  "WI": [
    "IA",
    "IL",
    "MI",
    "MN"
  ],
  "MI": [
    "IN",
    "OH",
    "WI"
  ],
  "MA": [
    "CT",
    "NH",
    "NY",
    "RI",
    "VT"
  ],
  "OR": [
    "CA",
    "ID",
    "NV",
    "WA"
  ],
  "SD": [
    "IA",
    "MN",
    "MT",
    "ND",
    "NE",
    "WY"
  ],
  "CT": [
    "MA",
    "NJ",
    "NY",
    "RI"
  ],
  "RI": [
    "CT",
    "MA"
  ],
  "WY": [
    "CO",
    "ID",
    "MT",
    "NE",
    "SD",
    "UT"
  ],
  "IA": [
    "IL",
    "MN",
    "MO",
    "NE",
    "SD",
    "WI"
  ],
  "IL": [
    "IA",
    "IN",
    "KY",
    "MO",
    "WI"
  ],
  "IN": [
    "IL",
    "KY",
    "MI",
    "OH"
  ],
  "OH": [
    "IN",
    "KY",
    "MI",
    "PA",
    "WV"
  ],
  "PA": [
    "DE",
    "MD",
    "NJ",
    "NY",
    "OH",
    "VA",
    "WV"
  ],
  "NJ": [
    "CT",
    "DE",
    "NY",
    "PA"
  ],
  "CA": [
    "AZ",
    "NV",
    "OR"
  ],
  "NV": [
    "AZ",
    "CA",
    "ID",
    "OR",
    "UT"
  ],
  "UT": [
    "AZ",
    "CO",
    "ID",
    "NV",
    "WY"
  ],
  "NE": [
    "CO",
    "IA",
    "KS",
    "MO",
    "SD",
    "WY"
  ],
  "DE": [
    "MD",
    "NJ",
    "PA"
  ],
  "CO": [
    "KS",
    "NE",
    "NM",
    "OK",
    "UT",
    "WY"
  ],
  "MO": [
    "AR",
    "IA",
    "IL",
    "KS",
    "KY",
    "NE",
    "OK",
    "TN"
  ],
  "KY": [
    "IL",
    "IN",
    "MO",
    "OH",
    "TN",
    "VA",
    "WV"
  ],
  "WV": [
    "KY",
    "OH",
    "PA",
    "VA"
  ],
  "VA": [
    "KY",
    "MD",
    "NC",
    "PA",
    "TN",
    "WV"
  ],
  "MD": [
    "DE",
    "PA",
    "VA"
  ],
  "KS": [
    "CO",
    "MO",
    "NE",
    "OK"
  ],
  "HI": [],
  "AZ": [
    "CA",
    "NM",
    "NV",
    "UT"
  ],
  "NM": [
    "AZ",
    "CO",
    "OK",
    "TX"
  ],
  "OK": [
    "AR",
    "CO",
    "KS",
    "MO",
    "NM",
    "TX"
  ],
  "TN": [
    "AL",
    "AR",
    "GA",
    "KY",
    "MO",
    "MS",
    "NC",
    "VA"
  ],
  "NC": [
    "GA",
    "SC",
    "TN",
    "VA"
  ],
  "AR": [
    "LA",
    "MO",
    "MS",
    "OK",
    "TN",
    "TX"
  ],
  "TX": [
    "AR",
    "LA",
    "NM",
    "OK"
  ],
  "MS": [
    "AL",
    "AR",
    "LA",
    "TN"
  ],
  "AL": [
    "FL",
    "GA",
    "MS",
    "TN"
  ],
  "GA": [
    "AL",
    "FL",
    "NC",
    "SC",
    "TN"
  ],
  "SC": [
    "GA",
    "NC"
  ],
  "LA": [
    "AR",
    "MS",
    "TX"
  ],
  "FL": [
    "AL",
    "GA"
  ]
};


export const stateNames: { [key: string]: string } = {
  "AL": "Alabama", "AK": "Alaska", "AZ": "Arizona", "AR": "Arkansas", "CA": "California",
  "CO": "Colorado", "CT": "Connecticut", "DE": "Delaware", "FL": "Florida", "GA": "Georgia",
  "HI": "Hawaii", "ID": "Idaho", "IL": "Illinois", "IN": "Indiana", "IA": "Iowa",
  "KS": "Kansas", "KY": "Kentucky", "LA": "Louisiana", "ME": "Maine", "MD": "Maryland",
  "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota", "MS": "Mississippi", "MO": "Missouri",
  "MT": "Montana", "NE": "Nebraska", "NV": "Nevada", "NH": "New Hampshire", "NJ": "New Jersey",
  "NM": "New Mexico", "NY": "New York", "NC": "North Carolina", "ND": "North Dakota", "OH": "Ohio",
  "OK": "Oklahoma", "OR": "Oregon", "PA": "Pennsylvania", "RI": "Rhode Island", "SC": "South Carolina",
  "SD": "South Dakota", "TN": "Tennessee", "TX": "Texas", "UT": "Utah", "VT": "Vermont",
  "VA": "Virginia", "WA": "Washington", "WV": "West Virginia", "WI": "Wisconsin", "WY": "Wyoming"
};

